### ISSUE TITLE
playlist menu stays open

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/streampusher-frontend#173]
![1662137280468](https://user-images.githubusercontent.com/2829501/188201330-1e9776f3-3933-43ce-ac9e-bb61a46cea1e.gif)
on the Media page, when you change the selected playlist, the menu doesn't disappear after making your selection

**Comment by mcfiredrill** [comment]
Thanks for the report, fixed here https://github.com/datafruits/streampusher-frontend/commit/ebd441efb8f4e1e1d41d7c6ef6e9c596f2ad71d4
