### ISSUE TITLE
creating new tag fails

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/streampusher-frontend#175]
when you try adding a new tag to a recording (when you edit the track from the media page), it doesn't seem to save and a flash error appears at the top (Sorry, something went wrong) when you press enter to submit the tag

![1663301646023](https://user-images.githubusercontent.com/2829501/190555758-f04ea617-6f46-46ef-b688-daff9feac342.gif)

saw this in the console log when inspecting
![messageImage_1663301712124](https://user-images.githubusercontent.com/2829501/190555814-06e1463e-5dba-4d09-b792-1b3bbfe3719d.jpg)

**Comment by mcfiredrill** [comment]
Thanks, fixed in https://github.com/datafruits/streampusher-api/commit/f86e6963c504ccd9e050ff55f563e4e9fdc48a16
